### ISSUE TITLE
How to Configure HTTPS for YOURLS using Docker Compose

### ISSUE THREAD

**Issue by Hobeom** [guessi/docker-yourls#15]
I am using the `guessi/docker-yourls` Docker image to deploy a YOURLS server and I'm looking to set up HTTPS for the server. I am currently unclear on how to adjust the Docker Compose configuration to support HTTPS.

Could you provide guidance on what changes need to be made to the Docker Compose file to enable HTTPS? Specifically, I'm looking for advice on how to integrate SSL certificates with the existing Docker setup and any required changes to the Nginx or web server configurations that might be included in the Docker image.

**Comment by guessi** [comment]
Hi @HoBeom 

There are several ways to archive the same goal to serve HTTPS (at least 10 in my head), depends on how/where you run the application.

Talking about the certificate, easiest way to get one is to apply from [Let's Encrypt](https://letsencrypt.org) and integrate into your reverse proxy's configuration. Maybe you can try [Caddy](https://caddyserver.com/) as simple solution, try to search `nginx/apache/Caddy + docker-compose` you should find many blogs tutorials out there.

**Comment by Hobeom** [comment]
Thank you, I was able to successfully configure SSL thanks to your guidance. After experimenting with various setups, I found that using SWAG (Secure Web Application Gateway) was the easiest and most effective solution. Below, I’m sharing the Docker Compose configuration example I used.

```yaml
 version: '3.7'
 services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - env.mysql
    volumes:
      - type: volume
        source: mysql-data
        target: /var/lib/mysql
        read_only: false
      - type: bind
        source: ./volumes/docker-entrypoint-initdb.d
        target: /docker-entrypoint-initdb.d
        read_only: true
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "30"

  yourls:
    image: guessi/docker-yourls:1.9.2
    container_name: yourls
    links:
      - mysql:mysql
    env_file:
      - env.yourls
    #ports:
    #  - 80:80
    #  - 443:443
    depends_on:
      - mysql
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: "30"

  swag:
    image: linuxserver/swag:latest
    container_name: swag
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=<your_timezone>
      - URL=<your_domain_url>
      - VALIDATION=http
      - EMAIL=<your_email>
    volumes:
      - ./swag/config:/config
    ports:
      - 80:80
      - 443:443
    depends_on:
      - yourls

volumes:
  mysql-data:
```
In this setup, the SWAG container automatically obtains an SSL certificate from Let's Encrypt and applies HTTPS to the YOURLS server.
Additionally, to complete the setup, you need to move the yourls.subdomain.conf.sample file from the swag/config/nginx/proxy-confs directory to the swag/config/nginx/site-confs directory. This step is crucial to ensure that the YOURLS site is properly configured for SSL and subdomain handling.
By moving this file, you enable the SWAG container to correctly proxy requests to your YOURLS instance using the specified subdomain, ensuring that your site is accessible over HTTPS.

I hope this solution helps others as well!
